
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(
    git
    macos
    docker
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

prompt_dir() {
    prompt_segment blue black "${PWD##*/}"
}

prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment green default "%(!.%{%F{yellow}%}.)"
  fi
}

alias vi='nvim'
alias vim='nvim'
alias dc='docker-compose'
alias dm='docker-machine'
alias ipy='ipython'
alias pt='poetry'

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="$HOME/.local/bin:$PATH"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init -)"
